# Stylistic Conventions {-}

I use the following conventions throughout this book:

-   **Abstract variables**: Abstract variables, i.e. variables that do not
represent specific objects in an example, are in `ALL CAPS TYPEWRITER TEXT`.

-   **Clickable buttons**: Clickable Buttons are in `typewriter text`.

-   **Code**: All code is in `typewriter text`.

-   **File names and directories**: File names and directories more generally are
printed in *italics*. I use CamelBack for file and directory names.

-   **File extensions**: Like file names, file extensions are *italicized*.

-   **Individual variable values**: Individual variable values mentioned in the
text are in *italics*.

-   **Objects**: Objects are printed in *italics*. I use underscores (`_`) to 
separate words in object names.

-   **Object columns**: Data frame object columns are printed in **bold**.

-   **R Function names** are followed by parentheses (e.g., `stats::lm()`)

-   **Packages**: **R** packages are printed in *italics*. When a system, rather than the package that shares its name is referred to, it is not italicized, e.g. R Markdown (system) vs. *rmarkdown* (package).[^system_names]

-   **Windows and RStudio panes**: Open windows and RStudio panes are written in
*italics*.

-   **Variable names**: Variable names are printed in **bold**. I use underscores (`_`) to separate words in variable names.


[^system_names]: See Yihui Xie's comment at: <https://andrewgelman.com/2016/01/14/rstanarm-and-more/#comment-259425>. Posted 14 January 2016.