<!---
 Chapter Chapter 5 For Reproducible Research in R and RStudio
 Christopher Gandrud
 Created 28/06/2012 05:48:16 pm KST
 Updated 
--->

\chapter{Chapter 5: Gathering Data with R}

# Importing locally stored data sets

## Single files

## Looping through multiple files


# Importing data sets from the internet

## Data from non-secure (`http`) URLs

<!-- Google docs -->

## Data from secure (`https`) URLs

## Data APIs & feeds

There are growing number of commands that can gather data directly from their sources and import them into **R**. Needless to say, this is great for reproducible research since it not only makes the data gathering process easier (you don't have to download a ton of Excel files and fiddle around with them before even getting the data into **R**), but it also makes replicating the data gathering process much more straightforward. Some examples include:

- The *openair* package, which beyond providing a number of tools for analysing air quality data also has the ability to directly gather data directly from sources such as Kings College London's London Air (<http://www.londonair.org.uk/>) database with the `importKCL` command.

# Basic web scraping 

## Scraping tables


## Gathering and parsing text