<!---
 Chapter Chapter 6 For Reproducible Research in R and RStudio
 Christopher Gandrud
 Created 28/06/2012 05:48:16 pm KST
 Updated 29 June 2012
--->

\chapter{Chapter 6: Storing, Versioning, Collaborating, and Accessing Files}

A stumbling block to actually reproducing a piece of research is getting a hold of the datasets and the codebooks that describe the data used in an analysis. <!-- Complete -->

Researchers often face a number of data management issues that, beyond making their research difficult to reproduce, can make doing the initial research difficult.

First, there is the problem of **storing** the data so that it is protected against computer failure--virus infections, dropping your laptop on the floor, and so on. 

Second, when 


 the data set can often grow and become disorganized. Perhaps even during a data transformation  This creates problems  
 
You can solve all of these problems in a couple of different ways using free or low cost cloud-based storage formats. In this chapter we will learn how to use **Dropbox** and **GitHub** for data:

- storage,

- version control,

- accessing, 

- and collaboration.

# Saving data in reproducible formats

Before getting into the details of cloud-based data storage, lets just consider what type of formats you should actually save your data in. A key issue for reproducibility is that others be able to not only get ahold of the exact data you used in your analysis, but be able to understand and use the data not only now, but in the future. Some file formats make this easier than others.

**R** is able to read (and write) a very wide variety of file formats, mostly through the `foreign` package in `base` **R**. This includes  <!-- Complete ---> 

# Storing data in the cloud


# Dropbox

Probably the easiest types of cloud storage for your research are services like **Dropbox** and **Google Drive**. These services typically involve a folder based on your computer's hard drive that is automatically synced with a similar folder on a cloud-based server. Typically you can sign up for the service for free and receive a limited amount of storage space (usually a few gigabytes worth, which should be plenty if your research is made up of text files.).

Most of these services not only store your data in the cloud, but also provide some way to share files and maybe even includes basic version control. I am going to focus on using **Dropbox** because it currently offers a complete set of features that allow you to store, version, collaborate, and access your data.

<!-- Complete -->

# GitHub

**Dropbox** does a fine job of meeting our four basic criteria for reproducible data storage. **GitHub** meets these criteria and more. 

<!--- Remember to explain what GitHub is in an earlier chapter --->

**GitHub** was not explicitly designed to host research projects or even data. It was designed to host 'socially coded' computer programs. It built an interface on top of the **git** version control system that makes it easy relatively easy for a number of collaborators to work together to build a computer program. This seems very far from reproducible research.

However, remember that as reproducible researchers we are just building projects out of interconnected text files. This is exactly the same as computer programming. and like computer programers, we need ways to store, version control, access, and collaborate on our text files. Because **GitHub** is very actively used by people with very similar needs (who are also really good programmers), the interface offers many highly developed and robust features for reproducible researchers.

Specifically, **GitHub**'s key features for us include: 

- **Git** is directly integrated into **RStudio** projects (**RStudio** also supports the **subversion** version control system, but I don't cover that here). 

- **Dropbox**'s version control system just lets you open old versions of your files. **git**'s version control system actually tracks every change you make. The **GitHub** website and GUI programs for Mac and Windows provide a nice interface for examining these changes.

