%%%%%%%%%%%%%%%
% Parent document for the book Reproducible Research with R and RStudio
% Christopher Gandrud
% Updated: 24 November 2012
%%%%%%%%%%%%%%

% Tell RStudio that weaving is to be done with the knitr package
% !Rnw weave = knitr

% Load required LaTeX packages
\documentclass[krantz1]{krantz}
\usepackage[authoryear]{natbib}
\usepackage{amssymb}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage{subfigure}
%\usepackage{epsfig}
\usepackage{makeidx}
%\usepackage{showidx}
\usepackage{multicol}
\frenchspacing
\tolerance=5000
\usepackage[usenames,dvipsnames,svgnames]{xcolor}
\usepackage{dcolumn}
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{lscape}
\usepackage{url}
\usepackage{todonotes}
\usepackage{tikz}
\usetikzlibrary{trees}
\usetikzlibrary{decorations.pathmorphing}
\usetikzlibrary{shapes,arrows}
\usepackage{wrapfig}

\newcommand{\blankpage}{
\newpage
\thispagestyle{empty}
\mbox{}
\newpage
}


% Set margins on highlighted code output boxes
\setlength\fboxsep{6.25mm}

% Set knitr global options
<<ParentGlobalOpts, echo=FALSE>>=
  options(width=50)
  opts_chunk$set(fig.align='center')
@

\makeatletter
\makeatother
\makeindex

\begin{document}

\SweaveOpts{concordance=TRUE}

% Title page
\title{Reproducible Research with R and RStudio}

\author{Christopher Gandrud}

\maketitle

% Set roman numeral page counter
\pagenumbering{roman}

% Front matter
\frontmatter

\blankpage
\blankpage
\blankpage
\blankpage

% Preface
<<ChildFrontMatterAuthor, child=c('/git_repositories/Rep-Res-Book/Source/FrontMatter/Preface.Rnw'), eval=TRUE, message=FALSE>>=
@

% Table of Contents
\tableofcontents

% Convert Stylistic Conventions child documnet from Markdown to LaTex and include
\chapter*{Stylistic Conventions}\label{StylisticConventions}

<<ChildStylisticConventions, echo=FALSE, messages=FALSE, results='hide', engine="sh">>=
pandoc /git_repositories/Rep-Res-Book/Source/FrontMatter/StylisticConventions.md -t latex -o /git_repositories/Rep-Res-Book/Temp/StyleTemp.tex
@

\input{/git_repositories/Rep-Res-Book/Temp/StyleTemp.tex}

% Include page on installing R packages used in the book
<<ChildFrontPackages, child=c('/git_repositories/Rep-Res-Book/Source/FrontMatter/Packages.Rnw')>>=
@

\listoffigures
\listoftables


\mainmatter

% Start arabic numeral page counter
\setcounter{page}{1}

% Part 1, include child documents
\part{Getting Started}

<<Child1, echo=FALSE, child=c('/git_repositories/Rep-Res-Book/Source/Children/Chapter1/chapter1.Rnw', '/git_repositories/Rep-Res-Book/Source/Children/Chapter2/chapter2.Rnw', '/git_repositories/Rep-Res-Book/Source/Children/Chapter3/chapter3.Rnw', '/git_repositories/Rep-Res-Book/Source/Children/Chapter4/chapter4.Rnw'), eval=TRUE, message=FALSE>>=
@

% Part 2, include child documents
\part{Data Gathering and Storage}

<<Child2, child=c('/git_repositories/Rep-Res-Book/Source/Children/Chapter5/chapter5.Rnw', '/git_repositories/Rep-Res-Book/Source/Children/Chapter6/chapter6.Rnw', '/git_repositories/Rep-Res-Book/Source/Children/Chapter7/chapter7.Rnw'), eval=TRUE, message=FALSE>>=
@

% Part 3, include child documents
\part{Analysis and Results}

<<Child3, child=c('/git_repositories/Rep-Res-Book/Source/Children/Chapter8/chapter8.Rnw', '/git_repositories/Rep-Res-Book/Source/Children/Chapter9/chapter9.Rnw', '/git_repositories/Rep-Res-Book/Source/Children/Chapter10/chapter10.Rnw'), eval=TRUE, message=FALSE>>=
@

% Part 4, include child documents
\part{Presentation Documents}

<<Child4, child=c('/git_repositories/Rep-Res-Book/Source/Children/Chapter11/chapter11.Rnw', '/git_repositories/Rep-Res-Book/Source/Children/Chapter12/chapter12.Rnw', '/git_repositories/Rep-Res-Book/Source/Children/Chapter13/chapter13.Rnw', '/git_repositories/Rep-Res-Book/Source/Children/Chapter14/chapter14.Rnw'), eval=TRUE, warning=FALSE>>=
@

% Include bibliotraphy
\bibliographystyle{apa}
\bibliography{/git_repositories/Rep-Res-Book/Source/rep-res-book.bib,/git_repositories/Rep-Res-Book/Source/rep-res-PackagesCited.bib}

% Include index
\clearpage
\printindex

\end{document}

