<!---
 Chapter Chapter 1 For Reproducible Research in R and RStudio
 Christopher Gandrud
 Created 28/06/2012 05:48:16 pm KST
 Updated 29 June 2012
--->

\chapter{Chapter 1: Introducing Reproducible Research}

# What is reproducible research?





# Why should research be reproducible?





# Who should read this book?

## Students


## Researchers


## Industry practitioners



# Why use R/RStudio for reproducible research?

<!--- Mention Org Mode --->


## Complete integration of data gathering, analysis, and presentation.


### Presentation

There are many LaTeX editors available, both open source and paid, as well as other ways to compile LaTeX documents, including directly through the command-line. **R** is capable of compiling LaTeX documents through <!--- complete --->. 

**RStudio** is actually as a very nice LaTeX editor. For creating documents that integrate markup and **R** code, at the moment it pretty much can't be beat. It has full syntax highlighting, even for documents with `knitr` code (which it can collapse when you just want to work on the text). It can spell check LaTeX documents. It handles `knitr` code chunks beautifully making it easy to navigate through complex documents and run individual chunks. 

Even if you aren't creating documents that integrate **R** code, *R* is still a decent full functioning LaTeX editor. It can insert common commands like `\section*{}` for unnumbered sections. <!--- Add explanation ---> Most importantly it easily compile LaTeX documents and show you a preview.


# Book overview

## What this book is not. 

This book describes a workflow for reproducible research primarily using **R** and **RStudio**. It is designed to give you the necessary tools to use this workflow for your own research. It is not designed to be a complete introduction to **R**, **RStudio**, **GitHub**, the command-line, or any other program that is a part of this workflow. Instead it shows you how these tools can fit together to make yourß research more reproducible.

To get the most out of these individual programs I point you to other resources that cover these programs in more detail. 

That being said, my goal in this for this book to be self-sufficient to the extent that a reader without a detailed understanding of these programs will be able to understand and use the commands and procedures I cover in this book. While learning how to use **R** and the other programs I often encountered examples that included commands, variables, and other things that were not well explained in the texts that I was reading. This caused me to waste many hours trying to figure out, for example, what the `$` in **R** is used for. I hope to save you from this wasted time by either providing a brief explanation of these possibly frustratingly mysterious conventions and/or pointing you in the direction of a good explanation. 

To that end, I can recommend a number of books for that cover more of the nitty-gritty of **R** and the command-line. 

- Michael J. Crawley's encyclopaedic **R** book, appropriately titled, **The R Book** published by Wiley.

- Norman Matloff's tour through the programming language aspects of **R** called **The Art of R Programming: A Tour of Statistical Design Software** published by No Starch Press.

- For an excellent introduction to the command-line in Linux and Mac, though with pretty clear implications for Windows users if they are running **PowerShell** (see Chapter 2) see William E. Shotts Jr.'s book *The Linux Command-line: A Complete Introduction* also published by No Starch Press.

- The **RStudio** website (<http://rstudio.org/docs/>) has a number of useful tutorials on how to use `knitr` with LaTeX and Markdown.

<!--- Maybe add LaTeX and GitHub books? --->

## How to read this book.

This book tells a story. It has a beginning, middle, and end. So, unlike a reference book it can and should be read like a novel, taking you through an empirical research processes from an empty folder maybe called `Research Paper` to a completed set of documents that showcase your findings.

That being said, readers with more experience using tools like **R** or \\( LaTeX \\) may want to skip over the nitty-gritty parts of the book that describe how to manipulate data frames or compile a \\( LaTeX \\) document into a PDF. Please feel free to do this. 

If you are experienced with **R** in particular you may want to skip over Chapter 3: Getting Started with **R**/**RStudio**.

## How this book was written

This book practices what it preaches. It can be reproduced. It was written using the programs and methods that it describes. Full documentation and source files can be found at the Book's **GitHub** repository. 

Feel free to read and even copy (within reason and with attribution, of course) the Book's source code. You can find it at <https://GitHub.com/christophergandrud/Rep-Res-Book>. This is especially useful if you want to know how to do something in the book that I don't directly cover in the text. 

In the same spirit, I encourage you to make your research files--not just data, but analysis code and markup--available for other researchers to learn from. 

Not only does reproducibility help us evaluate past work, but it also pushes forward knowledge in the scientific community.

## Contents overview.