<!---
 Chapter Chapter 9 For Reproducible Research in R and RStudio
 Christopher Gandrud
 Created 28/06/2012 05:48:16 pm KST
 Updated 4 July 2012 
--->

\chapter{Chapter 9: Showing Results with Tables}

Graphs and other visual methods, discussed in the next chapter, can often be a more affective way to present results than tables.[^tablerant] <!--- Maybe Cite ---> However, tables of results, descriptive statistics, and so on can sometimes still be an important part of communicating research. 

Creating tables by hand can be tedious no matter what program you are using to type up your results. Even more tedious is making changes to hand-created tables when you make changes to your data and models. Creating these tables can actually introduce new errors--post-analysis!--if you incorrectly copy what is in your **R** output. This is a very real possibility. The mind can go numb doing that sort of work. Also, creating tables by hand is not very reproducible. <!--- Build this point a bit --->

Fortunately, we don't actually need to create tables by hand. There are many ways to have **R** do the work for us. The goal of this chapter is to learn how to how to **automate table creation** for documents produced with both \LaTeX and Markdown/HTML. There are a number of ways to turn **R** objects into tables written in \LaTeX or HTML markup. In this chapter I mostly focus on the `xtable` and `texreg` packages. `xtable` can created tables for both of these markup languages. `texreg` only produces output for \LaTeX. `knitr` allows us to incorporate these tables directly into our documents. 

**Warning:** Automating table creation removes the possibility of adding errors to our analyses by incorrectly copying **R** output, which is a big potential problem in hand-created tables. Be warned, it is not an error free process. We could easily create inaccurate tables through coding errors. For example, we may incorrectly merge together columns in so that our id variables no longer match the data they are supposed to. 

So, as always, it is important to 'eyeball' the output. Does it make sense? If we picked a couple values in the **R** output do the match what is in our final table? If not, we need to go back to the code and see where things have gone wrong. With that caveat, lets start making tables. 

# Table Basics

Before getting into the details of how to create tables from **R** objects we need to first learn how generic tables are created in \LaTeX and Markdown. 

## Tables in \LaTeX

## Tables in Markdown

# Creating tables from R objects

## `xtable` & `texreg` basics with supported class objects

### `xtable` for \LaTeX

### `xtable` for Markdown

## `xtable` with non-supported class objects

## Basic `knitr` syntax for tables

The most important `knitr` chunk option for showing the markup created by these packages as tables is `results`. The `results` option can have three values:

- `markup`,

- `asis`,

- `hide`.

`hide` clearly hides the results of whatever we have in our code chunk; no results show up. 

# Tables with `apsrtable`

#


[^tablerant]: This is especially true of the small-print, high-density coefficient estimate tables that are sometimes descriptively called 'train schedule' tables.
