<!---
 Chapter Chapter 2 For Reproducible Research in R and RStudio
 Christopher Gandrud
 Created 28/06/2012 05:48:16 pm KST
 Updated 
--->

\chapter{Chapter 2: Getting Started with Reproducible Research}

# The Big Picture: A workflow for reproducible research

## Data Gathering

## Data Analysis

## Data Presentation



# Practical tips for reproducible research

## Document everything 



We'll discuss this more later in this chapter, but one important part of reproducible research with **R** is to *record your session info*. Many things in **R** stay the same over time, which makes it easy to recreate for future researchers to recreate what was done in the past. However, things do change from one version of **R** to another. Also, the way **R** functions may be slightly different on different operating systems. Finally, you may have **R** set to load packages by default. These packages might be necessary to run your code, but other people might not be able to easily know this from just looking at your source code. The `sessionInfo` command prints a record of all of these things.

## Everything is a (text) file

## All files should be human readable

## Research projects are many files tied together

## Have a plan to organize, store, and make your files available


# Introduction to the tools of reproducible research covered in this book

## **R**/**RStudio**

## `knitr`

## Cloud storage & versioning

## The command-line

## Markup languages: LaTeX & Markdown/HTML

  

