<!---
 Chapter Chapter 6 For Reproducible Research in R and RStudio
 Christopher Gandrud
 Created 28/06/2012 05:48:16 pm KST
 Updated 7 July 2012
--->

\chapter{Chapter 6: Storing, Collaborating, Accessing Files, Versioning}

A stumbling block to actually reproducing a piece of research is getting a hold of the datasets and the codebooks that describe the data used in an analysis. <!-- Complete -->

Researchers often face a number of data management issues that, beyond making their research difficult to reproduce, can make doing the initial research difficult.

First, there is the problem of **storing** the data so that it is protected against computer failure--virus infections, spilling coffee on your laptop, and so on.





Fourth, we almost never create a data set or write a paper perfectly all at once. We may make changes and then realize that we liked an earlier version, or parts of an earlier version better. This is a particularly important issue in data management where we may transform our data in unintended ways and want to go back to an earlier version. Collaborative projects can have regular incidents of one author accidentally deleting something in a file that another author needed, for example.

To deal with these issues we need to store our data in a system that has **version control**. Version control systems keep track of changes we make to our files and allow us to access previous versions if we like. 


 the data set can often grow and become disorganized. Perhaps even during a data transformation  This creates problems  
 
You can solve all of these problems in a couple of different ways using free or low cost cloud-based storage formats. In this chapter we will learn how to use **Dropbox** and **GitHub** for data:

- storage,

- accessing, 

- collaboration,

- version control.


# Saving data in reproducible formats

Before getting into the details of cloud-based data storage, lets just consider what type of formats you should actually save your data in. A key issue for reproducibility is that others be able to not only get ahold of the exact data you used in your analysis, but be able to understand and use the data not only now, but in the future. Some file formats make this easier than others.

**R** is able to read (and write) a very wide variety of file formats, mostly through the `foreign` package in `base` **R**. This includes  <!-- Complete ---> 

# Storing data in the cloud

Storing data locally--on your computer--or on a flash drive is generally more prone to loss than storing data on remote servers, often referred to as 'the cloud'. 


# Dropbox

The easiest types of cloud storage for your research are services like **Dropbox** and **Google Drive**. These services typically involve a folder based on your computer's hard drive that is automatically synced with a similar folder on a cloud-based server. Typically you can sign up for the service for free and receive a limited amount of storage space (usually a few gigabytes, which should be plenty if your research is made up of text files.).

Most of these services not only store your data in the cloud, but also provide some way to share files and maybe even includes basic version control. I am going to focus on using **Dropbox** because it currently offers a complete set of features that allow you to store, version, collaborate, and access your data.

## Version control

**Dropbox** has a simple version control system. Every time you save a document on **Dropbox** a new version is created. One the **Dropbox** website 

## Accessing Data

There are two similar, but importantly different ways to access data stored on **Dropbox**. All files stored on **Dropbox** have a URL address through which they can be access from computer connected to the internet. Some of these files can be easily loaded directly into **R**, while others must me manually (point-and-click) downloaded onto your computer and then loaded into **R**. The key factor is whether or not the files are located in your **Dropbox**'s *Public* folder. Files in the *Public* folder can be downloaded directly into *R*. Files not in the *Public* folder have to be downloaded manually.[^scrapeDropbox] 

Either way you find a file's URL address by first right-clicking on the file icon in you *Dropbox* folder. If the file is stored in the *Public* folder, you go to **Dropbox** then **Copy Public Link**. This copies the URL into your clipboard from where you can paste it into your **R** source code (or wherever). Once you have the URL you can load the file directly into **R** using the `read.table` command for dataframes or the `source` command for source files. This was covered in more detail in chapter GET.  


If the file is not in your *Public* folder you also go to **Dropbox** after right-clicking. Then choose **Get Link**. This will open a webpage in your default web browser from where you can download the file. You can copy and paste the page's URL from your browser's address bar. 

You can also get these URL links through the online version of your **Dropbox**. First log into the **Dropbox** website. When you hover your curser over a file (or folder) name you will see a chain icon appear on the far right. Clicking on this icon will get you the link.

<!--- Image? --->

Storing files in the *Public* folder clearly makes replication easier because the files can be downloaded and run directly in **R**. 

Note that you cannot save files through the URL link. You must save files in the **Dropbox** folder on your computer. 
<!-- Complete -->

# GitHub

**Dropbox** does a fine job of meeting our four basic criteria for reproducible data storage. **GitHub** meets these criteria and more. 

<!--- Remember to explain what GitHub is in an earlier chapter --->

**GitHub** was not explicitly designed to host research projects or even data. It was designed to host 'socially coded' computer programs. It built an interface on top of the **git** version control system that makes it easy relatively easy for a number of collaborators to work together to build a computer program. This seems very far from reproducible research.

However, remember that as reproducible researchers we are just building projects out of interconnected text files. This is exactly the same as computer programming. and like computer programers, we need ways to store, version control, access, and collaborate on our text files. Because **GitHub** is very actively used by people with very similar needs (who are also really good programmers), the interface offers many highly developed and robust features for reproducible researchers.

As is usually the case, **GitHub**'s added features mean that it is takes a longer time than **Dropbox** to set up and become familiar. So we need good reasons to want to invest the time needed to learn **GitHub** rather than just sticking with **Dropbox** or a similar service. Here is a list of **GitHub**'s key features relative to **Dropbox** for reproducible research: 

- **Git** is directly integrated into **RStudio** projects (**RStudio** also supports the **subversion** version control system, but I don't cover that here). 

- **Dropbox**'s version control system only lets you the see the file names, the times they were created, who created them, and revert back to specific versions. **git** tracks every change you make in a way that makes it relatively easy to find the version you want. The **GitHub** website and GUI programs for Mac and Windows provide nice interfaces for examining specific changes. You can also use the command-line to see changes.

- **Dropbox** creates a new version every time you save a file, which can make it difficult to actually find the version you want. **git**'s version control system only creates a new version when you tell it to. 

- **Dropbox** does not merge conflicting versions of a file together. This can be annoying when you are collaborating on project and more than one author is making changes to documents. **GitHub** identifies conflicts and lets you reconcile them.

- The **GitHub** website as an ''Issues'' area where you can to note and discuss issues you have while doing your research. Basically this is an interactive to-do list for your research project.

<!--- Complete --->

### Setting Up GitHub

There are a number of ways to set up **GitHub** on your computer. I will briefly cover both the command-line version (available for Windows, Mac, and Linux) and the GUI[^GUI] version currently available only for Windows and Mac. 

### Version Control in GitHub

**GitHub**'s version control system is much more comprehensive than **Dropbox**'. However, it also has a steeper learning curve. 

#### More Practice 

If you want more practice setting up **GitHub** in the command-line, **GitHub** and the website Code School have an interactive tutorial that you might find interesting. You can find it at: <http://try.GitHub.com/levels/1/challenges/4>.


[^GUI]: Graphical User Interface, i.e. not the command-line version, but the one with windows that you navigate with your mouse.

[^scrapeDropbox]: This is not completely true. It is possible to create a web scraper (see Chapter GET) that could download a data file from a file not in your *Public* folder. However, this is kind of a hassle and not practical, especially since the accessing files from the *Public* folder is so easy.


